name: PR Branch Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: 
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        uses: actions/github-script@v7
        with:
          script: |
            const head = context.payload.pull_request.head.ref;
            const base = context.payload.pull_request.base.ref;
            
            if (base === 'main' && head !== 'develop') {
              core.setFailed(`
                🚫 Invalid Branch Configuration
                
                - Source branch: ${head}
                - Target branch: ${base}
                
                Only PRs from 'develop' branch to 'main' branch are allowed.
                Please change your PR's base branch to 'develop'.
              `);
            } else {
              console.log(`
                ✅ Valid Branch Configuration
                
                - Source branch: ${head}
                - Target branch: ${base}
              `);
            }
